services:
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - lab2_net

  auth:
    build: ./auth_service
    container_name: auth
    environment:
      - SECRET_KEY=my_super_secret_lab_key
    networks:
      - lab2_net

  catalog-1:
    build: ./catalog_service
    container_name: catalog-1
    environment:
      - INSTANCE_NAME=catalog-1
      - PORT=8000
    networks:
      - lab2_net

  catalog-2:
    build: ./catalog_service
    container_name: catalog-2
    environment:
      - INSTANCE_NAME=catalog-2
      - PORT=8000
    networks:
      - lab2_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80" # Единая точка входа
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - catalog-1
      - catalog-2
    networks:
      - lab2_net

networks:
  lab2_net:
    driver: bridge