events {
    worker_connections 1024;
}

http {
    # Балансировщик для Catalog-сервиса
    upstream catalog_backend {
        server catalog-1:8000;
        server catalog-2:8000;
    }

    server {
        listen 80;

        # Маршрутизация на Auth-сервис
        location /auth/ {
            rewrite ^/auth/?(.*)$ /$1 break;
            proxy_pass http://auth:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Маршрутизация на Catalog-сервис (с балансировкой)
        location /catalog/ {
            rewrite ^/catalog/?(.*)$ /$1 break;
            proxy_pass http://catalog_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}